name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "0c3f72507d9c4e7d8b2985f4917e7cb2" }
]

[triggers]
crons = [ ]
